const countries = [
  {
    name: 'United States',
    iso2: 'US',
    iso3: 'USA',
    unicodeFlag: '🇺🇸',
    dial_code: '+1',
  },
  {
    name: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
    unicodeFlag: '🇳🇬',
    dial_code: '+234',
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    unicodeFlag: '🇬🇧',
    dial_code: '+44',
  },
  {
    name: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    unicodeFlag: '🇧🇩',
    dial_code: '+880',
  },
  {
    name: 'Belgium',
    iso2: 'BE',
    iso3: 'BEL',
    unicodeFlag: '🇧🇪',
    dial_code: '+32',
  },
  {
    name: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    unicodeFlag: '🇧🇫',
    dial_code: '+226',
  },
  {
    name: 'Bulgaria',
    iso2: 'BG',
    iso3: 'BGR',
    unicodeFlag: '🇧🇬',
    dial_code: '+359',
  },
  {
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    unicodeFlag: '🇧🇦',
    dial_code: '+387',
  },
  {
    name: 'Barbados',
    iso2: 'BB',
    iso3: 'BRB',
    unicodeFlag: '🇧🇧',
    dial_code: '+1 246',
  },
  {
    name: 'Wallis and Futuna',
    iso2: 'WF',
    iso3: 'WLF',
    unicodeFlag: '🇼🇫',
    dial_code: '+681',
  },
  {
    name: 'Bermuda',
    iso2: 'BM',
    iso3: 'BMU',
    unicodeFlag: '🇧🇲',
    dial_code: '+1 441',
  },
  {
    name: 'Bahrain',
    iso2: 'BH',
    iso3: 'BHR',
    unicodeFlag: '🇧🇭',
    dial_code: '+973',
  },
  {
    name: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
    unicodeFlag: '🇧🇮',
    dial_code: '+257',
  },
  {
    name: 'Benin',
    iso2: 'BJ',
    iso3: 'BEN',
    unicodeFlag: '🇧🇯',
    dial_code: '+229',
  },
  {
    name: 'Bhutan',
    iso2: 'BT',
    iso3: 'BTN',
    unicodeFlag: '🇧🇹',
    dial_code: '+975',
  },
  {
    name: 'Jamaica',
    iso2: 'JM',
    iso3: 'JAM',
    unicodeFlag: '🇯🇲',
    dial_code: '+1 876',
  },
  {
    name: 'Bouvet Island',
    iso2: 'BV',
    iso3: 'BVT',
    unicodeFlag: '🇧🇻',
    dial_code: '+55',
  },
  {
    name: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
    unicodeFlag: '🇧🇼',
    dial_code: '+267',
  },
  {
    name: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
    unicodeFlag: '🇼🇸',
    dial_code: '+685',
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    iso3: 'BRA',
    unicodeFlag: '🇧🇷',
    dial_code: '+55',
  },
  {
    name: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    unicodeFlag: '🇧🇸',
    dial_code: '+1 242',
  },
  {
    name: 'Jersey',
    iso2: 'JE',
    iso3: 'JEY',
    unicodeFlag: '🇯🇪',
    dial_code: '+44',
  },
  {
    name: 'Belarus',
    iso2: 'BY',
    iso3: 'BLR',
    unicodeFlag: '🇧🇾',
    dial_code: '+375',
  },
  {
    name: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    unicodeFlag: '🇧🇿',
    dial_code: '+501',
  },
  {
    name: 'Russia',
    iso2: 'RU',
    iso3: 'RUS',
    unicodeFlag: '🇷🇺',
    dial_code: '+7',
  },
  {
    name: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
    unicodeFlag: '🇷🇼',
    dial_code: '+250',
  },
  {
    name: 'Serbia',
    iso2: 'RS',
    iso3: 'SRB',
    unicodeFlag: '🇷🇸',
    dial_code: '+381',
  },
  {
    name: 'Timor-Leste',
    iso2: 'TL',
    iso3: 'TLS',
    unicodeFlag: '🇹🇱',
    dial_code: '+670',
  },
  {
    name: 'Réunion',
    iso2: 'RE',
    iso3: 'REU',
    unicodeFlag: '🇷🇪',
    dial_code: '+262',
  },
  {
    name: 'Turkmenistan',
    iso2: 'TM',
    iso3: 'TKM',
    unicodeFlag: '🇹🇲',
    dial_code: '+993',
  },
  {
    name: 'Tajikistan',
    iso2: 'TJ',
    iso3: 'TJK',
    unicodeFlag: '🇹🇯',
    dial_code: '+992',
  },
  {
    name: 'Romania',
    iso2: 'RO',
    iso3: 'ROU',
    unicodeFlag: '🇷🇴',
    dial_code: '+40',
  },
  {
    name: 'Tokelau',
    iso2: 'TK',
    iso3: 'TKL',
    unicodeFlag: '🇹🇰',
    dial_code: '+690',
  },
  {
    name: 'Guinea-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
    unicodeFlag: '🇬🇼',
    dial_code: '+245',
  },
  {
    name: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
    unicodeFlag: '🇬🇺',
    dial_code: '+1 671',
  },
  {
    name: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    unicodeFlag: '🇬🇹',
    dial_code: '+502',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    iso2: 'GS',
    iso3: 'SGS',
    unicodeFlag: '🇬🇸',
    dial_code: '+500',
  },
  {
    name: 'Greece',
    iso2: 'GR',
    iso3: 'GRC',
    unicodeFlag: '🇬🇷',
    dial_code: '+30',
  },
  {
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    iso3: 'GNQ',
    unicodeFlag: '🇬🇶',
    dial_code: '+240',
  },
  {
    name: 'Guadeloupe',
    iso2: 'GP',
    iso3: 'GLP',
    unicodeFlag: '🇬🇵',
    dial_code: '+590',
  },
  {
    name: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
    unicodeFlag: '🇯🇵',
    dial_code: '+81',
  },
  {
    name: 'Guyana',
    iso2: 'GY',
    iso3: 'GUY',
    unicodeFlag: '🇬🇾',
    dial_code: '+592',
  },
  {
    name: 'Guernsey',
    iso2: 'GG',
    iso3: 'GGY',
    unicodeFlag: '🇬🇬',
    dial_code: '+44',
  },
  {
    name: 'Georgia',
    iso2: 'GE',
    iso3: 'GEO',
    unicodeFlag: '🇬🇪',
    dial_code: '+995',
  },
  {
    name: 'Grenada',
    iso2: 'GD',
    iso3: 'GRD',
    unicodeFlag: '🇬🇩',
    dial_code: '+1 473',
  },
  {
    name: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
    unicodeFlag: '🇬🇦',
    dial_code: '+241',
  },
  {
    name: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    unicodeFlag: '🇸🇻',
    dial_code: '+503',
  },
  {
    name: 'Guinea',
    iso2: 'GN',
    iso3: 'GIN',
    unicodeFlag: '🇬🇳',
    dial_code: '+224',
  },
  {
    name: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
    unicodeFlag: '🇬🇲',
    dial_code: '+220',
  },
  {
    name: 'Greenland',
    iso2: 'GL',
    iso3: 'GRL',
    unicodeFlag: '🇬🇱',
    dial_code: '+299',
  },
  {
    name: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    unicodeFlag: '🇬🇮',
    dial_code: '+350',
  },
  {
    name: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
    unicodeFlag: '🇬🇭',
    dial_code: '+233',
  },
  {
    name: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
    unicodeFlag: '🇴🇲',
    dial_code: '+968',
  },
  {
    name: 'Tunisia',
    iso2: 'TN',
    iso3: 'TUN',
    unicodeFlag: '🇹🇳',
    dial_code: '+216',
  },
  {
    name: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
    unicodeFlag: '🇯🇴',
    dial_code: '+962',
  },
  {
    name: 'Croatia',
    iso2: 'HR',
    iso3: 'HRV',
    unicodeFlag: '🇭🇷',
    dial_code: '+385',
  },
  {
    name: 'Haiti',
    iso2: 'HT',
    iso3: 'HTI',
    unicodeFlag: '🇭🇹',
    dial_code: '+509',
  },
  {
    name: 'Hungary',
    iso2: 'HU',
    iso3: 'HUN',
    unicodeFlag: '🇭🇺',
    dial_code: '+36',
  },
  {
    name: 'Hong Kong',
    iso2: 'HK',
    iso3: 'HKG',
    unicodeFlag: '🇭🇰',
    dial_code: '+852',
  },
  {
    name: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    unicodeFlag: '🇭🇳',
    dial_code: '+504',
  },
  {
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    iso3: 'HMD',
    unicodeFlag: '🇭🇲',
    dial_code: '+672',
  },
  {
    name: 'Vatican City State (Holy See)',
    iso2: 'VA',
    iso3: 'VAT',
    unicodeFlag: '🇻🇦',
    dial_code: '+379',
  },
  {
    name: 'Puerto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    unicodeFlag: '🇵🇷',
    dial_code: '+1 939',
  },
  {
    name: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
    unicodeFlag: '🇵🇼',
    dial_code: '+680',
  },
  {
    name: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
    unicodeFlag: '🇵🇹',
    dial_code: '+351',
  },
  {
    name: 'Svalbard and Jan Mayen',
    iso2: 'SJ',
    iso3: 'SJM',
    unicodeFlag: '🇸🇯',
    dial_code: '+47',
  },
  {
    name: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    unicodeFlag: '🇵🇾',
    dial_code: '+595',
  },
  {
    name: 'Iraq',
    iso2: 'IQ',
    iso3: 'IRQ',
    unicodeFlag: '🇮🇶',
    dial_code: '+964',
  },
  {
    name: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    unicodeFlag: '🇵🇦',
    dial_code: '+507',
  },
  {
    name: 'French Polynesia',
    iso2: 'PF',
    iso3: 'PYF',
    unicodeFlag: '🇵🇫',
    dial_code: '+689',
  },
  {
    name: 'Papua New Guinea',
    iso2: 'PG',
    iso3: 'PNG',
    unicodeFlag: '🇵🇬',
    dial_code: '+675',
  },
  {
    name: 'Peru',
    iso2: 'PE',
    iso3: 'PER',
    unicodeFlag: '🇵🇪',
    dial_code: '+51',
  },
  {
    name: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    unicodeFlag: '🇵🇰',
    dial_code: '+92',
  },
  {
    name: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    unicodeFlag: '🇵🇭',
    dial_code: '+63',
  },
  {
    name: 'Pitcairn',
    iso2: 'PN',
    iso3: 'PCN',
    unicodeFlag: '🇵🇳',
    dial_code: '+870',
  },
  {
    name: 'Poland',
    iso2: 'PL',
    iso3: 'POL',
    unicodeFlag: '🇵🇱',
    dial_code: '+48',
  },
  {
    name: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
    unicodeFlag: '🇵🇲',
    dial_code: '+508',
  },
  {
    name: 'Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
    unicodeFlag: '🇿🇲',
    dial_code: '+260',
  },
  {
    name: 'Western Sahara',
    iso2: 'EH',
    iso3: 'ESH',
    unicodeFlag: '🇪🇭',
    dial_code: '+732',
  },
  {
    name: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
    unicodeFlag: '🇪🇪',
    dial_code: '+372',
  },
  {
    name: 'Egypt',
    iso2: 'EG',
    iso3: 'EGY',
    unicodeFlag: '🇪🇬',
    dial_code: '+20',
  },
  {
    name: 'Cocos (Keeling) Islands',
    iso2: 'CC',
    iso3: 'CCK',
    unicodeFlag: '🇨🇨',
    dial_code: '+61',
  },
  {
    name: 'South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    unicodeFlag: '🇿🇦',
    dial_code: '+27',
  },
  {
    name: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
    unicodeFlag: '🇪🇨',
    dial_code: '+593',
  },
  {
    name: 'Italy',
    iso2: 'IT',
    iso3: 'ITA',
    unicodeFlag: '🇮🇹',
    dial_code: '+39',
  },
  {
    name: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
    unicodeFlag: '🇻🇳',
    dial_code: '+84',
  },
  {
    name: 'Solomon Islands',
    iso2: 'SB',
    iso3: 'SLB',
    unicodeFlag: '🇸🇧',
    dial_code: '+677',
  },
  {
    name: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
    unicodeFlag: '🇪🇹',
    dial_code: '+251',
  },
  {
    name: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
    unicodeFlag: '🇸🇴',
    dial_code: '+252',
  },
  {
    name: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
    unicodeFlag: '🇿🇼',
    dial_code: '+263',
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    unicodeFlag: '🇸🇦',
    dial_code: '+966',
  },
  {
    name: 'Spain',
    iso2: 'ES',
    iso3: 'ESP',
    unicodeFlag: '🇪🇸',
    dial_code: '+34',
  },
  {
    name: 'Eritrea',
    iso2: 'ER',
    iso3: 'ERI',
    unicodeFlag: '🇪🇷',
    dial_code: '+291',
  },
  {
    name: 'Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
    unicodeFlag: '🇲🇪',
    dial_code: '+382',
  },
  {
    name: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
    unicodeFlag: '🇲🇬',
    dial_code: '+261',
  },
  {
    name: 'Morocco',
    iso2: 'MA',
    iso3: 'MAR',
    unicodeFlag: '🇲🇦',
    dial_code: '+212',
  },
  {
    name: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
    unicodeFlag: '🇲🇨',
    dial_code: '+377',
  },
  {
    name: 'Uzbekistan',
    iso2: 'UZ',
    iso3: 'UZB',
    unicodeFlag: '🇺🇿',
    dial_code: '+998',
  },
  {
    name: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    unicodeFlag: '🇲🇲',
    dial_code: '+95',
  },
  {
    name: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
    unicodeFlag: '🇲🇱',
    dial_code: '+223',
  },
  {
    name: 'Macau',
    iso2: 'MO',
    iso3: 'MAC',
    unicodeFlag: '🇲🇴',
    dial_code: '+853',
  },
  {
    name: 'Mongolia',
    iso2: 'MN',
    iso3: 'MNG',
    unicodeFlag: '🇲🇳',
    dial_code: '+976',
  },
  {
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    unicodeFlag: '🇲🇭',
    dial_code: '+692',
  },
  {
    name: 'Mauritius',
    iso2: 'MU',
    iso3: 'MUS',
    unicodeFlag: '🇲🇺',
    dial_code: '+230',
  },
  {
    name: 'Malta',
    iso2: 'MT',
    iso3: 'MLT',
    unicodeFlag: '🇲🇹',
    dial_code: '+356',
  },
  {
    name: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    unicodeFlag: '🇲🇼',
    dial_code: '+265',
  },
  {
    name: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    unicodeFlag: '🇲🇻',
    dial_code: '+960',
  },
  {
    name: 'Martinique',
    iso2: 'MQ',
    iso3: 'MTQ',
    unicodeFlag: '🇲🇶',
    dial_code: '+596',
  },
  {
    name: 'Northern Mariana Islands',
    iso2: 'MP',
    iso3: 'MNP',
    unicodeFlag: '🇲🇵',
    dial_code: '+1 670',
  },
  {
    name: 'Montserrat',
    iso2: 'MS',
    iso3: 'MSR',
    unicodeFlag: '🇲🇸',
    dial_code: '+1664',
  },
  {
    name: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
    unicodeFlag: '🇲🇷',
    dial_code: '+222',
  },
  {
    name: 'Isle of Man',
    iso2: 'IM',
    iso3: 'IMN',
    unicodeFlag: '🇮🇲',
    dial_code: '+44',
  },
  {
    name: 'Uganda',
    iso2: 'UG',
    iso3: 'UGA',
    unicodeFlag: '🇺🇬',
    dial_code: '+256',
  },
  {
    name: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
    unicodeFlag: '🇲🇾',
    dial_code: '+60',
  },
  {
    name: 'Mexico',
    iso2: 'MX',
    iso3: 'MEX',
    unicodeFlag: '🇲🇽',
    dial_code: '+52',
  },
  {
    name: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
    unicodeFlag: '🇮🇱',
    dial_code: '+972',
  },
  {
    name: 'France',
    iso2: 'FR',
    iso3: 'FRA',
    unicodeFlag: '🇫🇷',
    dial_code: '+33',
  },
  {
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    iso3: 'IOT',
    unicodeFlag: '🇮🇴',
    dial_code: '+246',
  },
  {
    name: 'Finland',
    iso2: 'FI',
    iso3: 'FIN',
    unicodeFlag: '🇫🇮',
    dial_code: '+358',
  },
  {
    name: 'Fiji',
    iso2: 'FJ',
    iso3: 'FJI',
    unicodeFlag: '🇫🇯',
    dial_code: '+679',
  },
  {
    name: 'Falkland Islands',
    iso2: 'FK',
    iso3: 'FLK',
    unicodeFlag: '🇫🇰',
    dial_code: '+500',
  },
  {
    name: 'Faroe Islands',
    iso2: 'FO',
    iso3: 'FRO',
    unicodeFlag: '🇫🇴',
    dial_code: '+298',
  },
  {
    name: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    unicodeFlag: '🇳🇮',
    dial_code: '+505',
  },
  {
    name: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
    unicodeFlag: '🇳🇱',
    dial_code: '+31',
  },
  {
    name: 'Norway',
    iso2: 'NO',
    iso3: 'NOR',
    unicodeFlag: '🇳🇴',
    dial_code: '+47',
  },
  {
    name: 'Namibia',
    iso2: 'NA',
    iso3: 'NAM',
    unicodeFlag: '🇳🇦',
    dial_code: '+264',
  },
  {
    name: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
    unicodeFlag: '🇻🇺',
    dial_code: '+678',
  },
  {
    name: 'New Caledonia',
    iso2: 'NC',
    iso3: 'NCL',
    unicodeFlag: '🇳🇨',
    dial_code: '+687',
  },
  {
    name: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
    unicodeFlag: '🇳🇪',
    dial_code: '+227',
  },
  {
    name: 'Norfolk Island',
    iso2: 'NF',
    iso3: 'NFK',
    unicodeFlag: '🇳🇫',
    dial_code: '+672',
  },
  {
    name: 'New Zealand',
    iso2: 'NZ',
    iso3: 'NZL',
    unicodeFlag: '🇳🇿',
    dial_code: '+64',
  },
  {
    name: 'Nepal',
    iso2: 'NP',
    iso3: 'NPL',
    unicodeFlag: '🇳🇵',
    dial_code: '+977',
  },
  {
    name: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
    unicodeFlag: '🇳🇷',
    dial_code: '+674',
  },
  {
    name: 'Niue',
    iso2: 'NU',
    iso3: 'NIU',
    unicodeFlag: '🇳🇺',
    dial_code: '+683',
  },
  {
    name: 'Cook Islands',
    iso2: 'CK',
    iso3: 'COK',
    unicodeFlag: '🇨🇰',
    dial_code: '+682',
  },
  {
    name: 'Ivory Coast',
    iso2: 'CI',
    iso3: 'CIV',
    unicodeFlag: '🇨🇮',
    dial_code: '+225',
  },
  {
    name: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    unicodeFlag: '🇨🇭',
    dial_code: '+41',
  },
  {
    name: 'Colombia',
    iso2: 'CO',
    iso3: 'COL',
    unicodeFlag: '🇨🇴',
    dial_code: '+57',
  },
  {
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    unicodeFlag: '🇨🇳',
    dial_code: '+86',
  },
  {
    name: 'Cameroon',
    iso2: 'CM',
    iso3: 'CMR',
    unicodeFlag: '🇨🇲',
    dial_code: '+237',
  },
  {
    name: 'Chile',
    iso2: 'CL',
    iso3: 'CHL',
    unicodeFlag: '🇨🇱',
    dial_code: '+56',
  },
  {
    name: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    unicodeFlag: '🇨🇦',
    dial_code: '+1',
  },
  {
    name: 'Congo',
    iso2: 'CG',
    iso3: 'COG',
    unicodeFlag: '🇨🇬',
    dial_code: '+242',
  },
  {
    name: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
    unicodeFlag: '🇨🇫',
    dial_code: '+236',
  },
  {
    name: 'Czech Republic',
    iso2: 'CZ',
    iso3: 'CZE',
    unicodeFlag: '🇨🇿',
    dial_code: '+420',
  },
  {
    name: 'Cyprus',
    iso2: 'CY',
    iso3: 'CYP',
    unicodeFlag: '🇨🇾',
    dial_code: '+357',
  },
  {
    name: 'Christmas Island',
    iso2: 'CX',
    iso3: 'CXR',
    unicodeFlag: '🇨🇽',
    dial_code: '+61',
  },
  {
    name: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    unicodeFlag: '🇨🇷',
    dial_code: '+506',
  },
  {
    name: 'Cape Verde',
    iso2: 'CV',
    iso3: 'CPV',
    unicodeFlag: '🇨🇻',
    dial_code: '+238',
  },
  {
    name: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    unicodeFlag: '🇨🇺',
    dial_code: '+53',
  },
  {
    name: 'Swaziland',
    iso2: 'SZ',
    iso3: 'SWZ',
    unicodeFlag: '🇸🇿',
    dial_code: '+268',
  },
  {
    name: 'Syria',
    iso2: 'SY',
    iso3: 'SYR',
    unicodeFlag: '🇸🇾',
    dial_code: '+963',
  },
  {
    name: 'Kyrgyzstan',
    iso2: 'KG',
    iso3: 'KGZ',
    unicodeFlag: '🇰🇬',
    dial_code: '+996',
  },
  {
    name: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    unicodeFlag: '🇰🇪',
    dial_code: '+254',
  },
  {
    name: 'Suriname',
    iso2: 'SR',
    iso3: 'SUR',
    unicodeFlag: '🇸🇷',
    dial_code: '+597',
  },
  {
    name: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    unicodeFlag: '🇰🇮',
    dial_code: '+686',
  },
  {
    name: 'Cambodia',
    iso2: 'KH',
    iso3: 'KHM',
    unicodeFlag: '🇰🇭',
    dial_code: '+855',
  },
  {
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    unicodeFlag: '🇰🇳',
    dial_code: '+1 869',
  },
  {
    name: 'Comoros',
    iso2: 'KM',
    iso3: 'COM',
    unicodeFlag: '🇰🇲',
    dial_code: '+269',
  },
  {
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
    unicodeFlag: '🇸🇹',
    dial_code: '+239',
  },
  {
    name: 'Slovakia',
    iso2: 'SK',
    iso3: 'SVK',
    unicodeFlag: '🇸🇰',
    dial_code: '+421',
  },
  {
    name: 'South Korea',
    iso2: 'KR',
    iso3: 'KOR',
    unicodeFlag: '🇰🇷',
    dial_code: '+82',
  },
  {
    name: 'Slovenia',
    iso2: 'SI',
    iso3: 'SVN',
    unicodeFlag: '🇸🇮',
    dial_code: '+386',
  },
  {
    name: 'North Korea',
    iso2: 'KP',
    iso3: 'PRK',
    unicodeFlag: '🇰🇵',
    dial_code: '+850',
  },
  {
    name: 'Kuwait',
    iso2: 'KW',
    iso3: 'KWT',
    unicodeFlag: '🇰🇼',
    dial_code: '+965',
  },
  {
    name: 'Senegal',
    iso2: 'SN',
    iso3: 'SEN',
    unicodeFlag: '🇸🇳',
    dial_code: '+221',
  },
  {
    name: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    unicodeFlag: '🇸🇲',
    dial_code: '+378',
  },
  {
    name: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    unicodeFlag: '🇸🇱',
    dial_code: '+232',
  },
  {
    name: 'Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
    unicodeFlag: '🇸🇨',
    dial_code: '+248',
  },
  {
    name: 'Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
    unicodeFlag: '🇰🇿',
    dial_code: '+7',
  },
  {
    name: 'Cayman Islands',
    iso2: 'KY',
    iso3: 'CYM',
    unicodeFlag: '🇰🇾',
    dial_code: '+1345',
  },
  {
    name: 'Singapore',
    iso2: 'SG',
    iso3: 'SGP',
    unicodeFlag: '🇸🇬',
    dial_code: '+65',
  },
  {
    name: 'Sweden',
    iso2: 'SE',
    iso3: 'SWE',
    unicodeFlag: '🇸🇪',
    dial_code: '+46',
  },
  {
    name: 'Sudan',
    iso2: 'SD',
    iso3: 'SDN',
    unicodeFlag: '🇸🇩',
    dial_code: '+249',
  },
  {
    name: 'Dominican Republic',
    iso2: 'DO',
    iso3: 'DOM',
    unicodeFlag: '🇩🇴',
    dial_code: '+1 849',
  },
  {
    name: 'Dominica',
    iso2: 'DM',
    iso3: 'DMA',
    unicodeFlag: '🇩🇲',
    dial_code: '+1 767',
  },
  {
    name: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
    unicodeFlag: '🇩🇯',
    dial_code: '+253',
  },
  {
    name: 'Denmark',
    iso2: 'DK',
    iso3: 'DNK',
    unicodeFlag: '🇩🇰',
    dial_code: '+45',
  },
  {
    name: 'Germany',
    iso2: 'DE',
    iso3: 'DEU',
    unicodeFlag: '🇩🇪',
    dial_code: '+49',
  },
  {
    name: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    unicodeFlag: '🇾🇪',
    dial_code: '+967',
  },
  {
    name: 'Algeria',
    iso2: 'DZ',
    iso3: 'DZA',
    unicodeFlag: '🇩🇿',
    dial_code: '+213',
  },
  {
    name: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    unicodeFlag: '🇺🇾',
    dial_code: '+598',
  },
  {
    name: 'Mayotte',
    iso2: 'YT',
    iso3: 'MYT',
    unicodeFlag: '🇾🇹',
    dial_code: '+262',
  },
  {
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    iso3: 'UMI',
    unicodeFlag: '🇺🇲',
    dial_code: '+1581',
  },
  {
    name: 'Lebanon',
    iso2: 'LB',
    iso3: 'LBN',
    unicodeFlag: '🇱🇧',
    dial_code: '+961',
  },
  {
    name: 'Saint Lucia',
    iso2: 'LC',
    iso3: 'LCA',
    unicodeFlag: '🇱🇨',
    dial_code: '+1 758',
  },
  {
    name: 'Laos',
    iso2: 'LA',
    iso3: 'LAO',
    unicodeFlag: '🇱🇦',
    dial_code: '+856',
  },
  {
    name: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
    unicodeFlag: '🇹🇻',
    dial_code: '+688',
  },
  {
    name: 'Taiwan',
    iso2: 'TW',
    iso3: 'TWN',
    unicodeFlag: '🇹🇼',
    dial_code: '+886',
  },
  {
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    unicodeFlag: '🇹🇹',
    dial_code: '+1 868',
  },
  {
    name: 'Turkey',
    iso2: 'TR',
    iso3: 'TUR',
    unicodeFlag: '🇹🇷',
    dial_code: '+90',
  },
  {
    name: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    unicodeFlag: '🇱🇰',
    dial_code: '+94',
  },
  {
    name: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
    unicodeFlag: '🇱🇮',
    dial_code: '+423',
  },
  {
    name: 'Latvia',
    iso2: 'LV',
    iso3: 'LVA',
    unicodeFlag: '🇱🇻',
    dial_code: '+371',
  },
  {
    name: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
    unicodeFlag: '🇹🇴',
    dial_code: '+676',
  },
  {
    name: 'Lithuania',
    iso2: 'LT',
    iso3: 'LTU',
    unicodeFlag: '🇱🇹',
    dial_code: '+370',
  },
  {
    name: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
    unicodeFlag: '🇱🇺',
    dial_code: '+352',
  },
  {
    name: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
    unicodeFlag: '🇱🇷',
    dial_code: '+231',
  },
  {
    name: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    unicodeFlag: '🇱🇸',
    dial_code: '+266',
  },
  {
    name: 'Thailand',
    iso2: 'TH',
    iso3: 'THA',
    unicodeFlag: '🇹🇭',
    dial_code: '+66',
  },
  {
    name: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
    unicodeFlag: '🇹🇬',
    dial_code: '+228',
  },
  {
    name: 'Chad',
    iso2: 'TD',
    iso3: 'TCD',
    unicodeFlag: '🇹🇩',
    dial_code: '+235',
  },
  {
    name: 'Turks and Caicos Islands',
    iso2: 'TC',
    iso3: 'TCA',
    unicodeFlag: '🇹🇨',
    dial_code: '+1 649',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    unicodeFlag: '🇻🇨',
    dial_code: '+1 784',
  },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
    unicodeFlag: '🇦🇪',
    dial_code: '+971',
  },
  {
    name: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    unicodeFlag: '🇦🇩',
    dial_code: '+376',
  },
  {
    name: 'Antigua and Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    unicodeFlag: '🇦🇬',
    dial_code: '+1268',
  },
  {
    name: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    unicodeFlag: '🇦🇫',
    dial_code: '+93',
  },
  {
    name: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
    unicodeFlag: '🇦🇮',
    dial_code: '+1 264',
  },
  {
    name: 'Iceland',
    iso2: 'IS',
    iso3: 'ISL',
    unicodeFlag: '🇮🇸',
    dial_code: '+354',
  },
  {
    name: 'Armenia',
    iso2: 'AM',
    iso3: 'ARM',
    unicodeFlag: '🇦🇲',
    dial_code: '+374',
  },
  {
    name: 'Albania',
    iso2: 'AL',
    iso3: 'ALB',
    unicodeFlag: '🇦🇱',
    dial_code: '+355',
  },
  {
    name: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
    unicodeFlag: '🇦🇴',
    dial_code: '+244',
  },
  {
    name: 'Antarctica',
    iso2: 'AQ',
    iso3: 'ATA',
    unicodeFlag: '🇦🇶',
    dial_code: '+672',
  },
  {
    name: 'Argentina',
    iso2: 'AR',
    iso3: 'ARG',
    unicodeFlag: '🇦🇷',
    dial_code: '+54',
  },
  {
    name: 'Australia',
    iso2: 'AU',
    iso3: 'AUS',
    unicodeFlag: '🇦🇺',
    dial_code: '+61',
  },
  {
    name: 'Austria',
    iso2: 'AT',
    iso3: 'AUT',
    unicodeFlag: '🇦🇹',
    dial_code: '+43',
  },
  {
    name: 'Aruba',
    iso2: 'AW',
    iso3: 'ABW',
    unicodeFlag: '🇦🇼',
    dial_code: '+297',
  },
  {
    name: 'India',
    iso2: 'IN',
    iso3: 'IND',
    unicodeFlag: '🇮🇳',
    dial_code: '+91',
  },
  {
    name: 'Azerbaijan',
    iso2: 'AZ',
    iso3: 'AZE',
    unicodeFlag: '🇦🇿',
    dial_code: '+994',
  },
  {
    name: 'Ireland',
    iso2: 'IE',
    iso3: 'IRL',
    unicodeFlag: '🇮🇪',
    dial_code: '+353',
  },
  {
    name: 'Indonesia',
    iso2: 'ID',
    iso3: 'IDN',
    unicodeFlag: '🇮🇩',
    dial_code: '+62',
  },
  {
    name: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    unicodeFlag: '🇺🇦',
    dial_code: '+380',
  },
  {
    name: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
    unicodeFlag: '🇶🇦',
    dial_code: '+974',
  },
  {
    name: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
    unicodeFlag: '🇲🇿',
    dial_code: '+258',
  },
];

export const getCurrencyValue = {
  NGN: {
    countryName: 'Nigeria',
    minimum: 100,
    maximum: 824000,
  },
  GHS: {
    countryName: 'Ghana',
    minimum: 10,
    maximum: 122000,
  },
  SZL: {
    countryName: 'Eswatini',
    minimum: 2,
    maximum: 20000,
  },
  KES: {
    countryName: 'Kenya',
    minimum: 15,
    maximum: 156000,
  },
  TZS: {
    countryName: 'Tanzania',
    minimum: 250,
    maximum: 2638000,
  },
  TRY: {
    countryName: 'Turkey',
    minimum: 3.5,
    maximum: 35000,
  },
  XAF: {
    countryName: 'Central African CFA',
    minimum: 65,
    maximum: 655000,
  },
  XOF: {
    countryName: 'West African CFA',
    minimum: 65,
    maximum: 655000,
  },
  CDF: {
    countryName: 'Democratic Republic of the Congo',
    minimum: 285,
    maximum: 2846000,
  },
  GNF: {
    countryName: 'Guinea',
    minimum: 930,
    maximum: 9312000,
  },
  SLE: {
    countryName: 'Sierra Leone',
    minimum: 2,
    maximum: 24000,
  },
  ETB: {
    countryName: 'Ethiopia',
    minimum: 6,
    maximum: 58000,
  },
  MZN: {
    countryName: 'Mozambique',
    minimum: 7,
    maximum: 67000,
  },
  ZWL: {
    countryName: 'Zimbabwe',
    minimum: 40,
    maximum: 381000,
  },
  RWF: {
    countryName: 'Rwanda',
    minimum: 125,
    maximum: 1277000,
  },
  ZAR: {
    countryName: 'South Africa',
    minimum: 2,
    maximum: 20000,
  },
  UGX: {
    countryName: 'Uganda',
    minimum: 400,
    maximum: 3963000,
  },
  ZMW: {
    countryName: 'Zambia',
    minimum: 2,
    maximum: 21000,
  },
  EGP: {
    countryName: 'Egypt',
    minimum: 3,
    maximum: 32000,
  },
  TND: {
    countryName: 'Tunisia',
    minimum: 0.5,
    maximum: 3300,
  },
  GMD: {
    countryName: 'Gambia',
    minimum: 7,
    maximum: 68000,
  },
  MWK: {
    countryName: 'Malawi',
    minimum: 120,
    maximum: 1153000,
  },
  ARS: {
    countryName: 'Argentina',
    minimum: 35,
    maximum: 368000,
  },
  BRL: {
    countryName: 'Brazil',
    minimum: 0.5,
    maximum: 5000,
  },
  BOB: {
    countryName: 'Bolivia',
    minimum: 0.7,
    maximum: 7000,
  },
  CLP: {
    countryName: 'Chile',
    minimum: 100,
    maximum: 957000,
  },
  COP: {
    countryName: 'Colombia',
    minimum: 400,
    maximum: 4316000,
  },
  PEN: {
    countryName: 'Peru',
    minimum: 0.4,
    maximum: 4000,
  },
  MXN: {
    countryName: 'Mexico',
    minimum: 1,
    maximum: 18000,
  },
  VES: {
    countryName: 'Venezuela',
    minimum: 360000,
    maximum: 36040000,
  },
  USD: {
    countryName: 'United States',
    minimum: 0.1,
    maximum: 1000,
  },
  HTG: {
    countryName: 'Haiti',
    minimum: 15,
    maximum: 140000,
  },
  CUP: {
    countryName: 'Cuba',
    minimum: 2.5,
    maximum: 25000,
  },
  DOP: {
    countryName: 'Dominican Republic',
    minimum: 6,
    maximum: 59000,
  },
  PYG: {
    countryName: 'Paraguay',
    minimum: 750,
    maximum: 7690000,
  },
  PAB: {
    countryName: 'Panama',
    minimum: 0.1,
    maximum: 1000,
  },
  UYU: {
    countryName: 'Uruguay',
    minimum: 5,
    maximum: 40000,
  },
  CRC: {
    countryName: 'Costa Rica',
    minimum: 60,
    maximum: 563000,
  },
  AMD: {
    countryName: 'Armenia',
    minimum: 40,
    maximum: 412000,
  },
  KHR: {
    countryName: 'Cambodia',
    minimum: 450,
    maximum: 4346000,
  },
  CNY: {
    countryName: 'China',
    minimum: 0.7,
    maximum: 7000,
  },
  BDT: {
    countryName: 'Bangladesh',
    minimum: 10,
    maximum: 116000,
  },
  CYP: {
    countryName: 'Cyprus',
    minimum: 0.1,
    maximum: 1000,
  },
  GEL: {
    countryName: 'Georgia',
    minimum: 0.1,
    maximum: 2500,
  },
  HKD: {
    countryName: 'Hong Kong',
    minimum: 0.8,
    maximum: 8000,
  },
  INR: {
    countryName: 'India',
    minimum: 8,
    maximum: 87000,
  },
  IDR: {
    countryName: 'Indonesia',
    minimum: 1600,
    maximum: 16399000,
  },
  JPY: {
    countryName: 'Japan',
    minimum: 15,
    maximum: 157000,
  },
  JOD: {
    countryName: 'Jordan',
    minimum: 0.1,
    maximum: 700,
  },
  MYR: {
    countryName: 'Malaysia',
    minimum: 0.4,
    maximum: 4500,
  },
  LBP: {
    countryName: 'Lebanon',
    minimum: 1500,
    maximum: 15862000,
  },
  PHP: {
    countryName: 'Philippines',
    minimum: 6,
    maximum: 60000,
  },
  KRW: {
    countryName: 'South Korea',
    minimum: 150,
    maximum: 1425000,
  },
  SGD: {
    countryName: 'Singapore',
    minimum: 0.1,
    maximum: 1000,
  },
  VND: {
    countryName: 'Vietnam',
    minimum: 2500,
    maximum: 25570000,
  },
  MOP: {
    countryName: 'Macau',
    minimum: 0.8,
    maximum: 8500,
  },
  TWD: {
    countryName: 'Taiwan',
    minimum: 3,
    maximum: 33500,
  },
  THB: {
    countryName: 'Thailand',
    minimum: 4,
    maximum: 38000,
  },
  EUR: {
    countryName: 'Eurozone',
    minimum: 0.1,
    maximum: 1000,
  },
  AOA: {
    countryName: 'Angola',
    minimum: 89,
    maximum: 890000,
  },
  RUB: {
    countryName: 'Russia',
    minimum: 1,
    maximum: 100000,
  },
};

export const countryToCurrencyMap = {
  nigeria: 'NGN',
  ghana: 'GHS',
  eswatini: 'SZL',
  kenya: 'KES',
  tanzania: 'TZS',
  turkey: 'TRY',
  'central-african-cfa': 'XAF',
  'west-african-cfa': 'XOF',
  congo: 'CDF',
  guinea: 'GNF',
  'sierra-leone': 'SLE',
  ethiopia: 'ETB',
  mozambique: 'MZN',
  zimbabwe: 'ZWL',
  rwanda: 'RWF',
  'south-africa': 'ZAR',
  uganda: 'UGX',
  zambia: 'ZMW',
  egypt: 'EGP',
  tunisia: 'TND',
  gambia: 'GMD',
  malawi: 'MWK',
  argentina: 'ARS',
  brazil: 'BRL',
  bolivia: 'BOB',
  chile: 'CLP',
  colombia: 'COP',
  peru: 'PEN',
  mexico: 'MXN',
  venezuela: 'VES',
  'united-states': 'USD',
  haiti: 'HTG',
  cuba: 'CUP',
  'dominican-republic': 'DOP',
  paraguay: 'PYG',
  panama: 'PAB',
  uruguay: 'UYU',
  'costa-rica': 'CRC',
  armenia: 'AMD',
  cambodia: 'KHR',
  china: 'CNY',
  bangladesh: 'BDT',
  cyprus: 'CYP',
  georgia: 'GEL',
  'hong-kong': 'HKD',
  india: 'INR',
  indonesia: 'IDR',
  japan: 'JPY',
  jordan: 'JOD',
  malaysia: 'MYR',
  lebanon: 'LBP',
  philippines: 'PHP',
  'south-korea': 'KRW',
  singapore: 'SGD',
  vietnam: 'VND',
  macau: 'MOP',
  taiwan: 'TWD',
  thailand: 'THB',
  eurozone: 'EUR',
  angola: 'AOA',
  russia: 'RUB',
};

function sanitizeCountryInput(country: string) {
  return country
    .toString()
    .normalize('NFD')
    .toLowerCase()
    .trim()
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export function getCountryShortCode(country: string): string {
  const sanitizedCountry = sanitizeCountryInput(country);
  return (
    countries.find((item) => item?.name?.toLowerCase() === sanitizedCountry)
      ?.iso2 || 'US'
  ).toLowerCase();
}

export function getCountryByShortCode(shortCode: string): string {
  const sanitizedCountryCode = shortCode?.toLowerCase();
  return (
    countries.find((item) => item?.iso2?.toLowerCase() === sanitizedCountryCode)
      ?.name || 'United States'
  ).toLowerCase();
}

export function getCurrencyByCountry(country: string): string {
  const sanitizedCountry = sanitizeCountryInput(country);
  return countryToCurrencyMap[sanitizedCountry] || null;
}

export default countries;
